{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpsetupintentlastsetuperrortype\/apiconnection"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPSetupIntentLastSetupErrorTypeAPIConnection) ","kind":"text"},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"apiConnection","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType\/apiConnection"},"abstract":[{"text":"An error connecting to Stripe’s API.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeAPIConnection","role":"symbol","title":"STPSetupIntentLastSetupErrorType.apiConnection","roleHeading":"Case","symbolKind":"case","modules":[{"name":"Stripe"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"apiConnection","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPSetupIntentLastSetupErrorType":{"title":"STPSetupIntentLastSetupErrorType","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stpsetupintentlastsetuperrortype","abstract":[{"type":"text","text":"The type of the error represented by "},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","abstract":[],"url":"\/documentation\/stripe","title":"Stripe","kind":"symbol","role":"collection","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPSetupIntentLastSetupErrorType/apiConnection":{"title":"STPSetupIntentLastSetupErrorType.apiConnection","type":"topic","url":"\/documentation\/stripe\/stpsetupintentlastsetuperrortype\/apiconnection","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"apiConnection","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSetupIntentLastSetupErrorType\/apiConnection","abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}]}}}